services:
  mariadb:
    image: 'mariadb:11.4'
    environment:
      - 'MARIADB_DATABASE=blog_tag'
      - 'MARIADB_PASSWORD=root'
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_USER=root'
    ports:
      - '3306'
