services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb11-lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: tag
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
