spring:
  application:
    name: blog-tag-service
  datasource:
    url: jdbc:mariadb://localhost:3306/tag
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080