spring:
  application:
    name: blog-tag-service
  datasource:
    url: jdbc:mariadb://localhost:3306/tag
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    graphiql:
      enabled: true        # aktifkan UI
server:
  port: 8080
  # opsional: ekspor SDL setiap build
dgs:
  graphql:
    schema-print:
      enabled: true        # menghasilkan build/schema.graphql
management:
  server:
    port: 8081        # port untuk manajemen
  endpoints:
    web:
      exposure:
        include: health, info        # atau '*' kalau mau semua
  endpoint:
    health:
      probes:
        enabled: true